# Generated by Django 5.0.2 on 2025-03-29 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('founder', models.CharField(max_length=200)),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.CharField(max_length=100)),
                ('last_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('main_image', models.ImageField(upload_to='campaign_images/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='campaign_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='campaign_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='campaign_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='campaign_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('upi', models.CharField(blank=True, max_length=50)),
                ('last_login_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated_date'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='main.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='main.userprofile')),
            ],
            options={
                'ordering': ['-investment_date'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='main.userprofile'),
        ),
    ]
