# Generated by Django 5.0.2 on 2025-03-30 12:34

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_campaign_image_path),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_campaign_image_path),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_campaign_image_path),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_campaign_image_path),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='main_image',
            field=models.ImageField(upload_to=main.models.get_campaign_image_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_profile_picture_path),
        ),
    ]
